cccfg-y := msc_x86_native_console_unicode_genasm

msc_x86_native_console_unicode_genasm-aflags-y :=
msc_x86_native_console_unicode_genasm-cflags-y :=
msc_x86_native_console_unicode_genasm-ldflag-y :=
