target-y := default

ifneq ($(filter msc,$(CONFIG_COMPILER)),)
ifneq ($(filter x64,$(CONFIG_COMPILER)),)
default-y := src/lang/coro/msc_x64/
else
default-y := src/lang/coro/msc_x86/
endif
else
ifneq ($(filter x64,$(CONFIG_COMPILER)),)
default-y := src/lang/coro/gnu_x64/
else
default-y := src/lang/coro/gnu_x86/
endif
endif

default-y += config/coro_test/ src/lang/prelude.o
default-binary-type := exe
